W5/W5D1/Capybara/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index]
  resources :comments, only: [:new, :create, :show]

end

W5/W5D1/Capybara/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, presence: true
  validate :require_sub
  after_save :set_subs
  before_update :require_sub_update
  after_update :set_subs

  has_many :comments, dependent: :destroy
  has_many :post_subs, dependent: :destroy

  has_many :subs,
    through: :post_subs,
    source: :sub,
    dependent: :destroy

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  attr_reader :sub_ids

  def require_sub_update
    # fail
    if @sub_ids.empty?
      self.errors["Post"] << "must have at least one sub."
    end
  end

  def require_sub
    @sub_ids ||= []
    if @sub_ids.empty?
      self.errors["Post"] << "must have at least one sub."
    end
  end

  def sub_ids=(sub_ids)
    @sub_ids = sub_ids
  end

  def set_subs
    PostSub.where(post_id: self.id).each do |post_sub|
      post_sub.destroy unless @sub_ids.include?(post_sub.sub_id)
    end

    @sub_ids.each do |sub_id|
      ps = PostSub.find_by(post_id: self.id, sub_id: sub_id)
      if ps.nil?
        PostSub.create(post_id: self.id, sub_id: sub_id)
      else
        PostSub.update(post_id: self.id, sub_id: sub_id)
      end
    end
  end

  def comments_by_parent_id
    comments_hash = Hash.new { |h, k| h[k] = [] }
    self.comments.includes(:author).each do |comment|
      comments_hash[comment.parent_comment_id] << comment
      # p comments_hash[comment.parent_comment_id]
    end
    # p comments
    comments_hash
  end
end

W5/W5D1/Capybara/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @sub_ids = params[:sub_ids]
    @sub_ids ||= []
    render :new
  end

  def create
    @post = Post.new(post_params)
    # fail
    if @post.save
      render :show
    else
      flash[:errors] = @post.errors.full_messages
      # fail
      redirect_to new_post_url(sub_ids: params[:post][:sub_ids])
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    # @all_comments = @post.comments.includes(:author)
    # fail
    @all_comments = @post.comments_by_parent_id
    render :show
  end

  def edit
    @post = Post.find_by(id: params[:id])
    @sub_ids = @post.subs.pluck(:id)
    render :edit
  end

  def update
    @post = Post.find_by(id: params[:id])
    @sub_ids = params[:post][:sub_ids]
    redirect_to subs_url if @post.nil?
    if @post.update(post_params)
      render :show
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to edit_post_url(sub_ids: params[:post][:sub_ids])
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    redirect_to subs_url if @post.nil?
    @post.destroy
    redirect_to subs_url
  end

  private
  def post_params
    params[:post][:author_id] = current_user.id
    # params[:sub_ids] ||= []
    # params[:post][:sub_ids] = params[:sub_ids]
    params.require(:post).permit(:title, :url, :content, :author_id, sub_ids: [])
  end
end

W5/W5D1/Capybara/app/helpers/posts_helper.rb
module PostsHelper
end

W5/W5D1/Capybara/app/views/posts/_form.html.erb
<form action="<%= action %>" method="post">
  <%= render "shared/form_auth" %>
  <% unless post.nil? %>
    <input type='hidden' name="_method" value="patch">
  <% end %>
  <table>
    <tr>
      <td>Title (required):</td>
      <td><input type="text" name="post[title]" value="<%=  post.title unless post.nil?%>"</td>
    </tr>
    <tr>
      <td>Url (optional):</td>
      <td><input type="text" name="post[url]" value="<%=  post.url unless post.nil?%>"</td>
    </tr>
    <tr>
      <td>Content (optional):</td>
      <td><textarea name="post[content]" cols=40 rows=5><%= post.content unless post.nil?%></textarea></td>
    </tr>
    <tr>
      <td>Subs (required):</td>
      <td>
        <% Sub.all.order(:title).each do |sub| %>
          <%= check_box_tag "post[sub_ids][]", sub.id, sub_ids.include?(sub.id)%>
            <%=  sub.title%>
        <% end %>
      </td>
    </tr>
    <tr>
      <td></td>
      <td>
        <input type="submit" value="Save">
      </td>
    </tr>
  </table>
</form>

W5/W5D1/Capybara/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render "form", post: @post, action: post_url(id: @post.id), sub_ids: @sub_ids %>

W5/W5D1/Capybara/app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render "form", post: nil, action: posts_url, sub_ids: @sub_ids %>

W5/W5D1/Capybara/app/views/posts/show.html.erb
<h1><%=  @post.title%></h1>
<table>
  <tr>
    <th>Author:</th>
    <td><%= @post.author.username%></td>
  </tr>
  <tr>
    <th>Title:</th>
    <td><%=  @post.title%></td>
  </tr>
  <tr>
    <th>URL:</th>
    <td><%=  @post.url%></td>
  </tr>
  <tr>
    <th>Content:</th>
    <td><%=  preserve_newline(@post.content)%></td>
  </tr>
  <tr>
    <th>Subs:</th>
    <td>
      <ul>
        <% @post.subs.each do |sub| %>
          <li>
            <%= link_to sub.title, sub_url(id: sub.id) %>
          </li>
        <% end %>
      </ul>
    </td>
  </tr>
</table>


<% if @post.author_id == current_user.id %>
  <%= link_to "Edit", edit_post_url(id: @post.id) %>
  <%= link_to "Delete", post_url(id: @post.id), method: :delete%>
<% end %>


<h2>Comments</h2>
<ul>
  <% @all_comments[nil].each do |comment| %>
    <li>
      <%= render "comments/comment", comment: comment %>
    </li>
  <% end %>

</ul>
<%= link_to "New Comment", new_comment_url(post_id: @post.id) %>