W5/W5D1/Capybara/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index]
  resources :comments, only: [:new, :create, :show]

end

W5/W5D1/Capybara/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  content           :text             not null
#  author_id         :integer          not null
#  post_id           :integer          not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  parent_comment_id :integer
#

class Comment < ActiveRecord::Base
  validates :content, :author_id, :post_id, presence: true
  belongs_to :post

  belongs_to :parent_comment,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :child_comments,
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User
end

W5/W5D1/Capybara/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post_id = params[:post_id]
    render :new
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to post_url(id: @comment.post_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to new_post_url(post_id: params[:post_id])
    end
  end

  def show
    @comment = Comment.find_by(id: params[:id])
    render :show
  end

  private
  def comment_params
    params[:comment][:author_id] = current_user.id
    params[:comment][:post_id] = params[:post_id]
    params[:comment][:parent_comment_id] = params[:parent_comment_id]
    params.require(:comment).permit(:content, :author_id, :post_id, :parent_comment_id)
  end
end

W5/W5D1/Capybara/app/helpers/comments_helper.rb
module CommentsHelper
end

W5/W5D1/Capybara/app/views/comments/_comment.html.erb
<%= link_to preserve_newline(comment.content), comment_url(comment.id) %> <span class="author"> - <%= comment.author.username %></span>
<ul>
  <% @all_comments[comment.id].each do |child| %>
    <li>
      <%= render "comments/comment", comment: child %>
    </li>
  <% end %>
</ul>

W5/W5D1/Capybara/app/views/comments/_form.html.erb
<form action='<%= action%>' method="post">
  <%= render "shared/form_auth" %>
  <textarea name="comment[content]" rows="8" cols="80"></textarea>
  <br>
  <input type="submit">
</form>

W5/W5D1/Capybara/app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render "form", action: comments_url(post_id: @post_id), comment: nil %>

W5/W5D1/Capybara/app/views/comments/show.html.erb
<br>
<table>
  <tr>
    <th>Comment:</th>
    <td><%=@comment.content%></td>
  </tr>
  <tr>
    <th>Author:</th>
    <td><%=@comment.author.username%></td>
  </tr>
  <tr>
    <th>Post:</th>
    <td><%=link_to @comment.post.title, post_url(id: @comment.post_id)%></td>
  </tr>
</table>

<h2>Reply</h2>
<%= render "form", action: comments_url(post_id: @comment.post_id, parent_comment_id: @comment.id), comment: nil %>