W5/W5D1/Capybara/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index]
  resources :comments, only: [:new, :create, :show]

end

W5/W5D1/Capybara/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  moderator_id :integer          not null
#  title        :string           not null
#  description  :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :moderator_id, :title, presence: true
  validates :title, uniqueness: true

  has_many :post_subs, dependent: :destroy
  has_many :posts,
    through: :post_subs,
    source: :post,
    dependent: :destroy

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User
end

W5/W5D1/Capybara/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :check_moderator, only: [:edit, :update]

  def new
    render :new
  end

  def create
    @sub = Sub.create(sub_params)
    if @sub.save
      render :show
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.update(sub_params)
      render :show
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def index
    render :index
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    if @sub
      @sub.destroy
    end
    redirect_to subs_url
  end

  private
  def sub_params    
    params[:sub][:moderator_id] = current_user.id
    params.require(:sub).permit(:moderator_id, :title, :description)
  end

  def check_moderator
    @sub = Sub.find_by(id: params[:id])
    if @sub && current_user.id != @sub.moderator_id
      flash[:error] = "You are not authorized to edit this sub."
      render :show
    end
  end
end

W5/W5D1/Capybara/app/helpers/subs_helper.rb
module SubsHelper
end

W5/W5D1/Capybara/app/views/subs/_form.html.erb
<form action="<%= action %>" method="post">
  <%= render "shared/form_auth" %>
  <% unless subreddit.nil? %>
    <input type='hidden' name="_method" value="patch">
  <% end %>
  <table>
    <tr>
      <td>Title:</td>
      <td><input type="text" name="sub[title]" value="<%=  subreddit.title unless subreddit.nil?%>"</td>
    </tr>
    <tr>
      <td>Description:</td>
      <td><textarea name="sub[description]" cols=60 rows=10><%= subreddit.description unless subreddit.nil?%></textarea></td>
    </tr>
    <tr>
      <td></td>
      <td>
        <input type="submit" value="Save">
      </td>
    </tr>
  </table>
</form>

W5/W5D1/Capybara/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<%= render "form", action: sub_url(id: @sub.id), subreddit: @sub%>

W5/W5D1/Capybara/app/views/subs/index.html.erb
<h2>Subs: </h2>
<table>
  <% Sub.all.order(:title).each do |subreddit| %>
    <tr>
      <td>
        <%= link_to subreddit.title, sub_url(id: subreddit.id) %>
      </td>
    </tr>
  <% end%>
  <tr>
    <td><br></td>
  </tr>
  <tr>
    <td>
      <%= link_to "Add Sub", new_sub_url %>
    </td>
  </tr>
</table>

W5/W5D1/Capybara/app/views/subs/new.html.erb
<h1>New Sub</h1>
<%= render "form", action: subs_url, subreddit: nil%>

W5/W5D1/Capybara/app/views/subs/show.html.erb
<h1><%=  @sub.title%></h1>
<table>
  <tr>
    <th>Moderator:</th>
    <td><%=  @sub.moderator.username%></td>
  </tr>
  <tr>
    <th>Description:</th>
    <td><%=  preserve_newline(@sub.description)%></td>
  </tr>
</table>

<% if @sub.moderator_id == current_user.id %>
  <%= link_to "Edit", edit_sub_url(id: @sub.id) %>
  <%= link_to "Delete", sub_url(id: @sub.id), method: :delete%>
<% end %>

<h2>Posts</h2>
<table>
  <% @sub.posts.each do |post| %>
    <tr>
      <td>
        <%= link_to post.title, post_url(post.id) %>
      </td>
    </tr>
  <% end %>
  <tr>
    <td><br></td>
  </tr>
  <tr>
    <td>
      <%= link_to "New Post", new_post_url(sub_ids: [@sub.id]) %>
    </td>
  </tr>
</table>